language: go

sudo: required

go:
  - 1.13.x
  - 1.14.x

install: true

script:
  - go test -v ./...
  - make build

matrix:
  allow_failures:
    - go: tip

branches:
  only:
    - /.*/
