/*
 * vnks
 *
 * <br/>https://nks.apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type ClusterInputBody struct {

	// 클러스터 이름
	Name *string `json:"name"`

	// 클러스터 타입
	ClusterType *string `json:"clusterType"`

	// 로그인 키 이름
	LoginKeyName *string `json:"loginKeyName"`

	// 쿠버네티스 버전
	K8sVersion *string `json:"k8sVersion,omitempty"`

	// Region의 코드
	RegionCode *string `json:"regionCode"`

	// zone 코드
	ZoneCode *string `json:"zoneCode,omitempty"`

	// Zone 번호
	ZoneNo *int32 `json:"zoneNo,omitempty"`

	// vpc의 No
	VpcNo *int32 `json:"vpcNo"`

	// 서브넷 No 목록
	SubnetNoList []*int32 `json:"subnetNoList"`

	// 로드밸런서 전용 서브넷 No
	SubnetLbNo *int32 `json:"subnetLbNo"`

	// log
	Log *ClusterLogInput `json:"log,omitempty"`

	// 기본 노드풀
	DefaultNodePool *DefaultNodePoolParam `json:"defaultNodePool,omitempty"`

	// 추가 노드풀
	NodePool []*NodePool `json:"nodePool,omitempty"`

	// InitScript 번호
	InitScriptNo *int32 `json:"initScriptNo,omitempty"`

	// Pod Security Policy 설정 여부
	PodSecurityPolicyEnabled *bool `json:"podSecurityPolicyEnabled,omitempty"`
}
