/*
 * vnks
 *
 * <br/>https://test0423.test-apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type ClusterRes struct {

	// 클러스터
	Cluster *Cluster `json:"cluster"`
}
