/*
 * vnks
 *
 * <br/>https://test0423.test-apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

import (
	"github.com/NaverCloudPlatform/ncloud-sdk-go-v2/ncloud"
	"os"
	"strings"
)

// contextKeys are used to identify the type of value in the context.
// Since these are string, it is possible to get a short description of the
// context key for logging and debugging using key.String().

type contextKey string

func (c contextKey) String() string {
	return "auth " + string(c)
}

func NewConfiguration(region string, apiKeys ...*ncloud.APIKey) *ncloud.Configuration {
	cfg := &ncloud.Configuration{
		BasePath:      "https://test0423.test-apigw.ntruss.com/vnks/v2",
		DefaultHeader: make(map[string]string),
		UserAgent:     "vnks//go",
	}
	if len(apiKeys) > 0 {
		cfg.APIKey = apiKeys[0]
	}
	cfg.InitCredentials()

	if os.Getenv("NCLOUD_API_GW") != "" {
		cfg.BasePath = os.Getenv("NCLOUD_API_GW") + "/vnks/v2"
		cfg.BasePath = strings.Replace(cfg.BasePath, "https://ncloud.", "https://nks.", 1)
		if region != "KR" {
			cfg.BasePath = strings.Replace(cfg.BasePath, "/vnks/v2", "/vnks/v2-"+strings.ToLower(region), 1)
		}
	}
	return cfg
}
