/*
 * vnks
 *
 * <br/>https://test0423.test-apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type CreateClusterRes struct {

	// 클러스터 UUID
	Uuid *string `json:"uuid,omitempty"`
}
