/*
 * vnks
 *
 * <br/>https://test0423.test-apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type GetOptionVersion200Response struct {
}

type Version struct {
	Value string `json:"value"`
	Label string `json:"label"`
}
