/*
 * vnks
 *
 * <br/>https://test0423.test-apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type NodePoolCreationBody struct {

	// 노드풀 이름
	Name *string `json:"name"`

	// 등록 될 노드 개수
	NodeCount *int32 `json:"nodeCount"`

	// Subnet 번호
	SubnetNo *int32 `json:"subnetNo,omitempty"`

	// 상품 코드
	ProductCode *string `json:"productCode"`
}
