/*
 * vnks
 *
 * <br/>https://test0423.test-apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type NodePoolsRes struct {

	// 노드풀 목록
	NodePool []*NodePoolRes `json:"nodePool"`
}
