/*
 * vnks
 *
 * <br/>https://nks.apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type NodePoolUpdateBody struct {

	// 노드 개수
	NodeCount *int32 `json:"nodeCount"`

	// 오토스케일
	Autoscale *AutoscalerUpdate `json:"autoscale,omitempty"`
}
