/*
 * vnks
 *
 * <br/>https://test0423.test-apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type NodePoolRes struct {
	// 인스턴스 No
	InstanceNo *int32 `json:"instanceNo"`

	// default pool 여부
	IsDefault *bool `json:"isDefault"`

	// 노드풀 이름
	Name *string `json:"name"`

	// 노드 개수
	NodeCount *int32 `json:"nodeCount"`

	// 서브넷 No 목록
	SubnetNoList []*int32 `json:"subnetNoList,omitempty"`

	// 상품 코드
	ProductCode *string `json:"productCode"`

	// 노드풀 상태
	Status *string `json:"status"`

	// 오토스케일
	Autoscale *AutoscaleOption `json:"autoscale"`
}

type NodePoolResList struct {
	NodePool []*NodePoolRes `json:"nodePool"`
}
