/*
 * vnks
 *
 * <br/>https://nks.apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type OptionRes struct {
	Label *string `json:"label"`

	Value *string `json:"value"`

	Disabled *bool `json:"disabled"`
}
