/*
 * vnks
 *
 * <br/>https://test0423.test-apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type WorkerNodeRes struct {

	// 워커노드 목록
	Nodes []*WorkerNode `json:"nodes"`
}
