/*
 * vnks
 *
 * <br/>https://nks.apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type WorkerNode struct {

	// 워커노드 id
	Id *string `json:"id"`

	// 워커노드 이름
	Name *string `json:"name"`

	// 워커노드 서버이름
	ServerName *string `json:"serverName"`

	// 워커노드 서버 스펙
	ServerSpec *string `json:"serverSpec"`

	// 비 공인 IP
	PrivateIp *string `json:"privateIp"`

	// 공인 IP
	PublicIp *string `json:"publicIp"`

	// 반납 보호 설정
	ReturnProtectionYn *string `json:"returnProtectionYn"`

	// 워커노드 현재 상태
	Status *string `json:"status"`

	// 상태 코드
	StatusCode *string `json:"statusCode"`

	// 상태 아이콘
	StatusIcon *string `json:"statusIcon"`

	// 상태 색깔
	StatusColor *string `json:"statusColor"`

	// 상태 이름
	StatusName *string `json:"statusName"`

	// 서버 이미지 이름
	ServerImageName *string `json:"serverImageName"`

	// cpu 수
	CpuCount *int32 `json:"cpuCount"`

	// 총 메모리 용량
	MemorySize *int32 `json:"memorySize"`

	// 스펙 코드
	SpecCode *string `json:"specCode"`

	// 로그인 키 이름
	LoginKeyName *string `json:"loginKeyName"`

	// 쿠버네티스 상태
	K8sStatus *string `json:"k8sStatus"`

	// 도커 버전
	DockerVersion *string `json:"dockerVersion"`

	// 커널 버전
	KernelVersion *string `json:"kernelVersion"`

	// 노드풀 이름
	NodePoolName *string `json:"nodePoolName"`
}
