name: "\U0001f4c4 Document Error"
description: "If you've found an error in the documentation."
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for raising a documentation issue!

        This form is meant to alert the maintainers to an issue with the provider documentation found on the [Terraform Registry](https://registry.terraform.io/providers/NaverCloudPlatform/ncloud/latest) (such as resource and data source documentation, guides and examples).

  - type: input
    id: docu_link
    attributes:
      label: Registry Documentation Link
      description: Please provide a link to the affected page on the Terraform Registry or examples.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please leave a brief description of the documentation issue.
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Where possible, please supply links to vendor documentation, other GitHub issues (open or closed) or pull requests that give additional context.

        [Information about referencing Github Issues](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests)
    validations:
      required: false

  - type: dropdown
    id: will_contribute
    attributes:
      label: Would you like to implement a fix?
      description: |
        If you plan to implement a fix for this, check this box to let the maintainers and community know (you can update this later if you change your mind).
      options:
        - "No"
        - "Yes"
    validations:
      required: false
