name: "\U0001F680 Feature Request"
description: "I have a suggestion (and might want to implement myself \U0001F642)!"
title: "[Feature]: "
labels: ["needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for opening a feature request!

        This form is intended as a way to request additional functionality for resources, data sources, or the provider itself. This may include requests such as adding additional arguments or attributes enabled by upstream API changes, additional validation for arguments, entirely new resource or data source, etc.

        When possible, it's helpful to check the [NCLOUD Go SDKv2](https://github.com/NaverCloudPlatform/ncloud-sdk-go-v2) to determine whether functionality exists to enable the requested feature. It is **not** required that you do this. Any references found when searching can be added to the "References" field below to give maintainers or the community a head start.

        Please update the title to match what you're requesting, e.g.:

        - `[New Resource]:` - for new resource requests
        - `[New Data Source]:` - for new data source requests

  - type: markdown
    attributes:
      value: |
        # Community Note

        * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
        * Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
        * If you are interested in working on this issue or have submitted a pull request, please leave a comment

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please leave a brief description of what you're requesting.
    validations:
      required: true

  - type: textarea
    id: affected
    attributes:
      label: Affected Resource(s) and/or Data Source(s)
      placeholder: "* ncloud_xxxxx"
    validations:
      required: false

  - type: textarea
    id: tf_config
    attributes:
      label: Potential Terraform Configuration
      description: |
        If this request was implemented, what might the Terraform configuration look like? A best guess is helpful, even if you're unsure of exactly what the end result will look like. This helps maintainers and the community better understand how you (someone who is in need of this feature) envisions it.

        **Note:** This field will render in HCL, so there is no need to add a [code fence](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).
      render: terraform
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Where possible, please supply links to vendor documentation, other GitHub issues (open or closed) or pull requests that give additional context.

        [Information about referencing Github Issues](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests)
    validations:
      required: false

  - type: dropdown
    id: will_contribute
    attributes:
      label: Would you like to implement a fix?
      description: |
        If you plan to implement a fix for this, check this box to let the maintainers and community know (you can update this later if you change your mind).
      options:
        - "No"
        - "Yes"
    validations:
      required: false
