name: "\U0001F914 Question"
description: "If you need help figuring something out."
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for raising an issue!

        This form is for asking questions.

        If you have a support request or question please submit them to one of these resources:

        * [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
        * [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please leave a detailed description of the issue.
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Where possible, please supply links to vendor documentation, other GitHub issues (open or closed) or pull requests that give additional context.

        [Information about referencing Github Issues](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests)
    validations:
      required: false

  - type: dropdown
    id: will_contribute
    attributes:
      label: Would you like to implement a fix?
      description: |
        If you plan to implement a fix for this, check this box to let the maintainers and community know (you can update this later if you change your mind).
      options:
        - "No"
        - "Yes"
    validations:
      required: false
